# Generated by Django 4.2.7 on 2025-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementidentifiertype',
            name='name',
            field=models.CharField(choices=[('ANDROID_UIAUTOMATOR', 'Android UIAutomator'), ('CLASS_NAME', 'Class Name'), ('ID', 'ID'), ('XPATH', 'XPath'), ('ACCESSIBILITY_ID', 'ACCESSIBILITY ID')], max_length=20, unique=True),
        ),
    ]
