# Generated by Django 4.2.7 on 2025-06-18 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststeptest',
            name='identifier_type',
        ),
        migrations.AddField(
            model_name='teststeptest',
            name='element_identifier_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_steps', to='api.elementidentifiertype'),
        ),
        migrations.AddField(
            model_name='teststeptest',
            name='input_field_type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teststeptest',
            name='input_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teststeptest',
            name='parameter_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
