# Generated by Django 4.2.7 on 2025-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teststeptest_element_screenshots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststeptest',
            name='action',
            field=models.CharField(choices=[('click', 'Click'), ('swap', 'Swap'), ('send_keys', 'Send Keys')], max_length=10),
        ),
    ]
