# Generated by Django 4.2.7 on 2025-06-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_teststeptest_identifier_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststep',
            name='element_screenshot',
        ),
        migrations.AlterField(
            model_name='teststep',
            name='element_identifier_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_step', to='api.elementidentifiertype'),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='input_field_type',
            field=models.CharField(blank=True, default='text', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='input_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teststep',
            name='parameter_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TestStepFake',
        ),
    ]
