# Generated by Django 4.2.7 on 2025-06-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_elementidentifiertype_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testexecution',
            old_name='executed_on',
            new_name='executed_device',
        ),
        migrations.RemoveField(
            model_name='testexecution',
            name='log_message',
        ),
        migrations.RemoveField(
            model_name='testexecution',
            name='parameters',
        ),
    ]
