# Generated by Django 4.2.7 on 2025-07-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_teststeptest_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassignment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.application'),
        ),
        migrations.AlterField(
            model_name='batchassignment',
            name='customgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customtestgroup'),
        ),
    ]
