# Generated by Django 4.2.7 on 2025-06-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_teststep_element_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='element_screenshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
