# Generated by Django 4.2.7 on 2025-06-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teststep_element_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teststep',
            old_name='elementID',
            new_name='element_id',
        ),
        migrations.RenameField(
            model_name='teststep',
            old_name='test_case',
            new_name='testcase',
        ),
        migrations.AlterUniqueTogether(
            name='teststep',
            unique_together={('testcase', 'step_order')},
        ),
    ]
