# Generated by Django 4.2.7 on 2025-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_input_teststep_actual_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststeptest',
            name='actual_input',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
