# Generated by Django 4.2.7 on 2025-07-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_batchassignment_application_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchassignment',
            unique_together={('name', 'assigned_by', 'application', 'customgroup')},
        ),
    ]
