# Generated by Django 4.2.7 on 2025-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teststeptest_actual_input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'verbose_name': 'Test Suite', 'verbose_name_plural': 'Test Suites'},
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='testsuite',
            unique_together={('application', 'name')},
        ),
    ]
