# Generated by Django 4.2.7 on 2025-07-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_batchassignment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchassignment',
            name='assignment_type',
        ),
    ]
