# Generated by Django 4.2.7 on 2025-06-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_elementid_teststep_element_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parser',
        ),
    ]
