# Generated by Django 4.2.7 on 2025-06-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_testsuite_options_alter_application_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('code', 'name', 'suite', 'application')},
        ),
    ]
