# Generated by Django 4.2.7 on 2025-07-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_batchassignment_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassignment',
            name='assignment_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.testtype'),
        ),
    ]
