# Generated by Django 4.2.7 on 2025-06-24 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_testcase_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('name', 'suite', 'application')},
        ),
        migrations.AlterField(
            model_name='testcase',
            name='created_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
