# Generated by Django 4.2.7 on 2025-08-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_batchassignment_assignment_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batchassignment',
            name='suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.testsuite'),
        ),
        migrations.AlterUniqueTogether(
            name='batchassignment',
            unique_together={('name', 'assigned_by', 'application', 'customgroup', 'suite')},
        ),
    ]
