# Generated by Django 4.2.7 on 2025-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_testcase_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepresult',
            old_name='test_start',
            new_name='time_start',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
