# Generated by Django 4.2.7 on 2025-07-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_test_start_stepresult_time_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='assigned_to',
        ),
    ]
