# Generated by Django 4.2.7 on 2025-07-06 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_device_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testexecution',
            name='device',
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='executed_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='api.device'),
        ),
    ]
