# Generated by Django 4.2.7 on 2025-07-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_testexecution_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexecution',
            name='overallstatus',
            field=models.CharField(blank=True, choices=[('passed', 'Completed_Passed'), ('failed', 'Completed_Failed'), ('in_progress', 'In_Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], max_length=20, null=True),
        ),
    ]
