# Generated by Django 4.2.7 on 2025-07-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_testexecution_overallstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
