# Generated by Django 4.2.7 on 2025-07-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_device_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='uuid',
            new_name='device_uuid',
        ),
    ]
