# Generated by Django 4.2.7 on 2025-07-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_uuid_device_device_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepresult',
            name='test_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teststeptest'),
        ),
    ]
