# Generated by Django 4.2.7 on 2025-07-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_stepresult_test_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepresult',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
