# Generated by Django 4.2.7 on 2025-06-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepresult',
            name='test_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
