# Generated by Django 4.2.7 on 2025-06-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stepresult_test_start_stepresult_time_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchassignment',
            name='suite',
        ),
        migrations.AddField(
            model_name='batchassignment',
            name='testcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcaseid', to='api.testcase'),
        ),
    ]
